"""
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""


def fibonacci(x):
    if x == 1:
        return 1
    if x == 2:
        return 2
    else:
        return fibonacci(x - 1) + fibonacci(x - 2)


fib_sum = 0
i = 1
while fibonacci(i) <= 4000000:
    if fibonacci(i) % 2 == 0:
        fib_sum += fibonacci(i)
    i += 1

print(fib_sum)
